import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "SMA Muhammadiyah 5 Makassar",
  description: "Generated by Mahiswa Universitas Muhammadiyah Makassar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>{children}</body>
    </html>
  );
}
